name: deploy
on:
  push:
    branches: master

jobs:
  terraform-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: "Terraform Apply"
        uses: ams0/terraform-apply-for-azure-action@v1
        with:
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          path: "ghes"
